#!/bin/sh

. /etc/rc.subr

name="www_kmx_io"
rcvar=www_kmx_io_enable

www_kmx_io_user=www_kmx_io
www_kmx_io_group=www_kmx_io

command="/home/www.kmx.io/start_"
_pidprefix="/var/run"
pidfile="${_pidprefix}/${name}.pid"

[ -z "$www_kmx_io_enable" ]     && www_kmx_io_enable="NO"

load_rc_config $name

run_rc_command "$1"
