
all: beetle oaa os pfem reed vulon

beetle: beetle.kmx.io.dmesg.txt
beetle.kmx.io.dmesg.txt:
	ssh beetle.kmx.io dmesg > beetle.kmx.io.dmesg.txt
.PHONY: beetle beetle.kmx.io.dmesg.txt

oaa: oaa.kmx.io.dmesg.txt
oaa.kmx.io.dmesg.txt:
	ssh oaa.kmx.io dmesg > oaa.kmx.io.dmesg.txt
.PHONY: oaa oaa.kmx.io.dmesg.txt

os: os.kmx.io.dmesg.txt
os.kmx.io.dmesg.txt:
	ssh os.kmx.io dmesg > os.kmx.io.dmesg.txt
.PHONY: os os.kmx.io.dmesg.txt

pfem: pfem.kmx.io.dmesg.txt
pfem.kmx.io.dmesg.txt:
	ssh pfem.kmx.io dmesg > pfem.kmx.io.dmesg.txt
.PHONY: pfem pfem.kmx.io.dmesg.txt

reed: reed.kmx.io.dmesg.txt
reed.kmx.io.dmesg.txt:
	ssh reed.kmx.io dmesg > reed.kmx.io.dmesg.txt
.PHONY: reed reed.kmx.io.dmesg.txt

vulon: vulon.kmx.io.dmesg.txt
vulon.kmx.io.dmesg.txt:
	ssh vulon.kmx.io dmesg > vulon.kmx.io.dmesg.txt
.PHONY: vulon vulon.kmx.io.dmesg.txt
